### PR TITLE
replace multiple tags with multiple values

### PR DESCRIPTION
**Pull request by matvaleriano**
I needed a way to replace each tag for its proper value ... and not just for a single value

### CODE REVIEW

**Comment by anseki** [comment]
Hi @mathvaleriano, thank you for the PR.

It seems that your test code doesn't test multiple values.
It should not be copy of `replaceTag.test.js`. Also, e.g. it should check difference values like `@foo1@`, `@foo2@`.
And also, the `.only` should be removed.

**Comment by anseki** [comment]
I merged it manually.

- The method should have an interface like others. e.g. it should accept `srcPath` and `pathTest`.
- It makes meaningless `arrayTags`.
- PRs should respect coding styles of target, such as indent, trailing whitespaces, line-break at end of file, etc.
- PRs should respect syntax, such as JavaScript (e.g. `replacement` is re-declared), JSDoc format (e.g. invalid `@param Array<{string, string}>`, missing `@returns`, see http://usejsdoc.org/), etc.
- More small changing can accept multiple values.
- Also, it seems that the code have other logical bugs.
- Also, it seems that the test code have problems.

Thank you for the PR 😄

**Comment by matvaleriano** [comment]
thanks .... i'll review that

**Comment by matvaleriano** [comment]
I expressed myself badly. I wanted to pass N tags, each of which would receive a set value, not multiple values. Sorry man

**Comment by anseki** [comment]
Doesn't new [`replaceTag` method](https://github.com/anseki/pre-proc#replacetag) implement your want?

If you want an interface of `replaceTagMultipleValues` you wrote, use this:

```js
function replaceTagMultipleValues(replacements, content, srcPath, pathTest) {
  var replacementArray = [];
  return preProc.replaceTag(replacements.reduce(function(tagArray, replacement) {
    tagArray.push(replacement.tag);
    replacementArray.push(replacement.replacement);
    return tagArray;
  }, []), replacementArray, content, srcPath, pathTest);
}
```

**Comment by matvaleriano** [comment]
nop

**Comment by anseki** [comment]
What do you mean "nop"?
Sorry, my English is poor. Could you explain, please?

**Pull request closed without merging**
